---
# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: types
output: internal/types/openapi.gen.go
generate:
  models: true
